source 'https://rubygems.org'
ruby '2.2.0'

gem 'rails', '4.2.2'
gem 'mysql2'
gem 'therubyracer'
gem 'less-rails'
gem 'uglifier'
gem 'sass-rails', '~> 5.0'
gem 'twitter-bootstrap-rails'
gem 'jquery-rails'
gem 'dotenv-rails'
# gem 'activeresource'
# gem 'activerecord-nulldb-adapter'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end
